- name: install docker
  hosts: all
  become: true
  tasks:
    - name: upgrade all packages
      ansible.builtin.yum: 
        name: '*'
        state: latest

    - name: Remove docker if installed from CentOS repo
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: Install yum utils
      ansible.builtin.yum:
        name: 
          - "yum-utils"
          - unzip 
        state: latest

    - name: Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: Add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
    - name: Ensure Python and pip are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    # - name: Install AWS CLI using pip
    #   pip:
    #     name: awscli
    #     state: present
    #     executable: pip3

    # - name: Verify AWS CLI installation
    #   command: aws --version
    #   register: aws_cli_version

    # - name: Display AWS CLI version
    #   debug:
    #     msg: "AWS CLI version: {{ aws_cli_version.stdout }}"

    - name: install aws cli
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/ec2-user/awscliv2.zip

    - name: unzip zip file
      ansible.builtin.unarchive:
        src: /home/ec2-user/awscliv2.zip
        dest: /home/ec2-user
        remote_src: True

    - name: run the installer
      ansible.builtin.command:
      args:
        cmd: "./aws/install"
        creates: /usr/local/bin/aws

    - name: Get ECR login password
      command: "/usr/local/bin/aws ecr get-login-password --region us-east-1"
      register: ecr_login_password


    - name: Login to ECR
      command: "docker login --username AWS --password-stdin 904602740498.dkr.ecr.us-east-1.amazonaws.com"
      args:
        stdin: "{{ ecr_login_password.stdout }}"

    # - name: log in to AWS ec2-user
    #   ansible.builtin.shell: |
    #     export PATH=/usr/local/bin:$PATH
    #     source ~/.bash_profile
    #     aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}