//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-0fe630eb857a6ec83"
mykey = "firstkey"
tags = ["postgresql", "nodejs", "react"]
instancetype = "t2.micro"
controlinstancetype = "t2.micro"
num = 3
region = "us-east-1"
mysecgr = "jenkins-project-208-sec-gr"
user = "harun"