- name: configure nodejs container
  hosts: _ansible_nodejs
  become: true
  # vars_files:
  #   - secret.yml
  environment:
    ecr_repo_name: "{ECR_REPO_NAME}/nodejs"
    # DB_HOST: "{{ hostvars['_ansible_postgresql'].postgresql_ip }}"
  tasks: 
    - name: remove nodejs container
      community.docker.docker_container:
        name: nodejs
        state: absent
        force_kill: true

    - name: remove nodejs image
      community.docker.docker_image:
        name: "{{ ecr_repo_name }}"
        state: absent

    - name: Pull Nodejs Image
      docker_image:
        name: "{{ ecr_repo_name }}"
        tag: latest
        source: pull

    - name: Run Nodejs Container
      docker_container:
        name: nodejs
        image: "{{ ecr_repo_name }}"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        env:
          DB_USER=postgres
          DB_PASSWORD=Pp123456789
          DB_NAME=clarustodo
          DB_PORT=5432
          DB_HOST=172.31.28.239
          