- name: configure react container
  hosts: _ansible_react
  become: true
  # vars_files:
  #   - secret.yml
  environment:
    ecr_repo_name: "{ECR_REPO_NAME}/react"
  tasks: 
    - name: remove react container
      community.docker.docker_container:
        name: react
        state: absent
        force_kill: true

    - name: remove react image
      community.docker.docker_image:
        name: "{{ ecr_repo_name }}"
        state: absent  
 
    - name: Pull React Image
      docker_image:
        name: "{{ ecr_repo_name }}"
        tag: latest
        source: pull

    - name: Run React Container
      docker_container:
        name: react
        image: "{{ ecr_repo_name }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        env:
          REACT_APP_BASE_URL: http://54.89.187.200:5000/
